blank_issues_enabled: false
contact_links:
  - name: Accurate Hitboxes on Modrinth
    url: https://modrinth.com/mod/accuratehitboxes
    about: Download the latest official releases of the mod here!
  - name: Accurate Hitboxes on CurseForge
    url: https://www.curseforge.com/minecraft/mc-mods/accuratehitboxes
    about: Download the latest official releases of the mod here!
