name: Feature Request
description: Suggest an idea or enhancement for Accurate Hitboxes
title: "[Feature Request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We are always looking for ways to improve Accurate Hitboxes! Describe your idea below.
  - type: textarea
    id: description
    attributes:
      label: Describe the feature you'd like to see
      description: What new functionality or enhancement are you proposing?
      placeholder: "I want this mod to be even more perfect."
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Is this suggestion a solution to an existing frustration or missing mechanic?
    validations:
      required: false
